apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.nativecameraview'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.nativecameraview"
  defaultConfig {
    minSdkVersion getDefaultMinSdkVersionForCurrentExpoSdkVersion()
    targetSdkVersion getDefaultTargetSdkVersionForCurrentExpoSdkVersion()
  }
  compileSdkVersion getDefaultCompileSdkVersionForCurrentExpoSdkVersion()
}

dependencies {
}
